[build]
  command = "python build.py"
  publish = "app/static"
  functions = "netlify_deploy"

[functions]
  external_node_modules = ["python-dotenv"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/wms_handler"
  status = 200
  force = true
