[build]
  publish = "app/static"
  functions = "functions"

[functions]
  external_node_modules = ["python-dotenv"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true
